/**
 * Geocoded coordinates for the Bali guide's places — generated by
 * scripts/harvest-honeymoon-coords.mts and committed so the seed needs no
 * network.
 *
 * EVERY ENTRY IS A GUESS. The seed writes them with needs_review = true and the
 * admin draws them with a dashed ring until you confirm each one.
 * 126 of 231 places are pinned;
 * the remaining 105 are pinned by hand.
 */

export interface SeedCoord { lat: number; lng: number; address: string }

export const SEED_COORDS: Record<string, SeedCoord> = {
    "La Brisa": {
        "lat": -8.65458,
        "lng": 115.124811,
        "address": "La Brisa, Jalan Pantai Batu Mejan, Canggu, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "FINNS Beach Club": {
        "lat": -8.666818,
        "lng": 115.139368,
        "address": "Bondi Bakehouse, Jalan Pantai Berawa, Tibubeneng, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "The Lawn Canggu": {
        "lat": -8.658496,
        "lng": 115.12976,
        "address": "the Lawn Canggu, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Potato Head Beach Club": {
        "lat": -8.679407,
        "lng": 115.149959,
        "address": "Potato Head Beach Club, No. 51B, Jalan Petitenget, Kerobokan Kelod, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Mrs Sippy": {
        "lat": -8.679649,
        "lng": 115.151054,
        "address": "Mrs Sippy, Jalan Petitenget, Kerobokan Kelod, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Deus Ex Machina Canggu": {
        "lat": -8.651246,
        "lng": 115.133385,
        "address": "Deus Ex Machina, 4, Jalan Batu Mejan, Canggu, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Black Sand Brewery": {
        "lat": -8.645585,
        "lng": 115.141275,
        "address": "Black Sand Brewery, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Green Door": {
        "lat": -8.668088,
        "lng": 115.146974,
        "address": "behind the green door, Jalan Pura Kayu Putih, Tibubeneng, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Old Man's": {
        "lat": -8.659045,
        "lng": 115.13086,
        "address": "Old Man's, 117X, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Sandbar Canggu": {
        "lat": -8.659554,
        "lng": 115.130285,
        "address": "Sandbar, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "La Favela": {
        "lat": -8.683873,
        "lng": 115.16288,
        "address": "La Favela Bali, 177 X, Jalan Kayu Aya, Seminyak, Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Mason's": {
        "lat": -8.653949,
        "lng": 115.131802,
        "address": "ATM HSBC Mason Pantai Batu Bolong, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Billy Ho": {
        "lat": -8.656981,
        "lng": 115.131332,
        "address": "Billy Ho, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Ulekan": {
        "lat": -8.66016,
        "lng": 115.143117,
        "address": "Ulekan, Jalan Tegal Sari, Tibubeneng, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Sensorium": {
        "lat": -8.649703,
        "lng": 115.13067,
        "address": "sensorium, Jalan Padang Linjong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Crate Cafe": {
        "lat": -8.648693,
        "lng": 115.137197,
        "address": "Crate Cafe, Jalan Canggu Padang Linjong, Canggu, North Kuta, Badung, Bali, 80351, Indonesia"
    },
    "Satu Satu": {
        "lat": -8.4743,
        "lng": 115.5292,
        "address": "Bukit Satu, Manggis, Karangasem, Bali, 80871, Indonesia"
    },
    "Nook Bali": {
        "lat": -8.669541,
        "lng": 115.161202,
        "address": "Nook, Jalan Umalas I, Kerobokan Kelod, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Bottega Italiana": {
        "lat": -8.653183,
        "lng": 115.132426,
        "address": "Bottega Italiana, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Milk & Madu Canggu": {
        "lat": -8.655321,
        "lng": 115.131967,
        "address": "Milk & Madu Beach Road, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "TIGA Canggu": {
        "lat": -8.656558,
        "lng": 115.134732,
        "address": "tiga, Jalan Nelayan, Canggu, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Tygr Sushi": {
        "lat": -8.660455,
        "lng": 115.141367,
        "address": "TYGR Sushi Bar, Jalan Pantai Berawa, Tibubeneng, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Rise Canggu": {
        "lat": -8.651781,
        "lng": 115.128517,
        "address": "Luna & Rise, Jalan Pantai Batu Mejan, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Honey Canggu": {
        "lat": -8.643791,
        "lng": 115.143762,
        "address": "Honey’s Fashion, Jalan Raya Kayutulang, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Front Canggu": {
        "lat": -8.646621,
        "lng": 115.140657,
        "address": "Clothes Store in Front of Casa Tua, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "AMO Spa": {
        "lat": -8.651337,
        "lng": 115.134663,
        "address": "AMO Spa, 69, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Spring Spa Canggu": {
        "lat": -8.654091,
        "lng": 115.131731,
        "address": "Spring Canggu Spa, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Therapy Spa Bali": {
        "lat": -8.682843,
        "lng": 115.164431,
        "address": "Therapy Day Spa, Jalan Kayu Aya, Kerobokan Kelod, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Jet Black Ginger": {
        "lat": -8.65419,
        "lng": 115.14219,
        "address": "Jet Black Ginger, Gang Jalak 20, Tibubeneng, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Warung Men Lari": {
        "lat": -8.527814,
        "lng": 115.172227,
        "address": "Warung Babi Guling Men Lari, Jalan Raya Denpasar - Singaraja, Poyan, Werdi Bhuwana, Mengwi, Badung, Bali, 82191, Indonesia"
    },
    "Varuna Warung": {
        "lat": -8.654754,
        "lng": 115.131733,
        "address": "Warung Varuna, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Warung Local Canggu": {
        "lat": -8.646754,
        "lng": 115.140533,
        "address": "Warung Local, 10, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Warung Men Agus": {
        "lat": -8.635864,
        "lng": 115.143197,
        "address": "Warung Nasi Babi Guling Men Agus, Jalan Raya Canggu, Canggu, North Kuta, Badung, Bali, 80351, Indonesia"
    },
    "Bali MMA": {
        "lat": -8.634527,
        "lng": 115.159481,
        "address": "Bali MMA, Jalan Raya Padonan, Tibubeneng, North Kuta, Badung, Bali, 80351, Indonesia"
    },
    "SOMA Bali": {
        "lat": -8.643683,
        "lng": 115.157329,
        "address": "Soma Fight Club, Jalan Raya Canggu, Kerobokan, Tibubeneng, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Jungle Paddle Bali": {
        "lat": -8.634945,
        "lng": 115.139718,
        "address": "Jungle Paddle, Jalan Sempol, Pengembungan, Pererenan, Mengwi, Badung, Bali, 80351, Indonesia"
    },
    "Bali Social Club": {
        "lat": -8.643081,
        "lng": 115.143844,
        "address": "Bali Social Club, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Tropical Nomad Coworking": {
        "lat": -8.65266,
        "lng": 115.138004,
        "address": "Tropical Nomad Coworking Space, Canggu Shortcut, Canggu, North Kuta, Badung, Bali, 08456, Indonesia"
    },
    "Outpost Canggu": {
        "lat": -8.657994,
        "lng": 115.140232,
        "address": "Outpost Canggu Coworking, 1, Gang Putih, Tibubeneng, North Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Lost Villa Bali": {
        "lat": -8.692756,
        "lng": 115.168057,
        "address": "Lost In Paradise Clothing Store, Jalan Raya Seminyak, Villa Kamboja, Seminyak, Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Aston Canggu Beach Resort": {
        "lat": -8.658147,
        "lng": 115.130849,
        "address": "Aston Canggu Beach Resort, Jalan Pantai Batu Bolong, Canggu, North Kuta, Badung, Bali, 80363, Indonesia"
    },
    "Tanah Lot Temple": {
        "lat": -8.621229,
        "lng": 115.086885,
        "address": "Tanah Lot Temple, Jalan Enjung Pura, Batugaing, Beraban, Kediri, Tabanan, Bali, 82121, Indonesia"
    },
    "Savaya Bali": {
        "lat": -8.846413,
        "lng": 115.140652,
        "address": "Savaya Bali, Path to Ocean, Pecatu, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Sundays Beach Club": {
        "lat": -8.847465,
        "lng": 115.151523,
        "address": "Sundays Beach Club, Gang Batu Bolong, Ungasan, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Ulu Cliffhouse": {
        "lat": -8.814066,
        "lng": 115.091524,
        "address": "Ulu Cliffhouse, Jalan Labuan Sait- Pecatu, Pecatu, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Karma Beach Bali": {
        "lat": -8.847763,
        "lng": 115.152976,
        "address": "Karma Beach, Ungasan, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "White Rock Beach Club": {
        "lat": -8.847747,
        "lng": 115.156155,
        "address": "White Rock Beach Club, Gang Batu Bolong, Ungasan, Kuta Selatan, Badung, Bali, 80361, Indonesia"
    },
    "Melasti Beach": {
        "lat": -8.848292,
        "lng": 115.157572,
        "address": "Melasti Beach, Ungasan, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Bingin Beach": {
        "lat": -8.80567,
        "lng": 115.113067,
        "address": "Bingin Beach, Pecatu, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Uluwatu Temple": {
        "lat": -8.829369,
        "lng": 115.084343,
        "address": "Uluwatu Temple, Jalan Labuan Sait- Pecatu, Pecatu, Kuta Selatan, Badung, Bali, 80361, Indonesia"
    },
    "Jimbaran Bay": {
        "lat": -8.783378,
        "lng": 115.159417,
        "address": "Four Seasons Bali at Jimbaran Bay, Jalan Pura Sekaang, Jimbaran, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Nusa Dua Beach": {
        "lat": -8.788464,
        "lng": 115.230217,
        "address": "Nusa Dua Beach, Benoa, Kuta Selatan, Badung, Bali, 80362, Indonesia"
    },
    "Folk Pool & Gardens": {
        "lat": -8.513879,
        "lng": 115.260238,
        "address": "Folk Pool & Gardens, Jalan Monkey Forest, Ubud, Ubud District, Gianyar, Bali, 80751, Indonesia"
    },
    "Tlaga Singha": {
        "lat": -8.591317,
        "lng": 115.267741,
        "address": "Tlaga Singha Bali, Jalan Jaga Raga, Celuk, Sukawati, Gianyar, Bali, 80582, Indonesia"
    },
    "Cretya Ubud by Alas Harum": {
        "lat": -8.440114,
        "lng": 115.280588,
        "address": "Cretya Ubud, Jalan I Wayan Lunga, Apuh, Tegallalang, Gianyar, Bali, 80561, Indonesia"
    },
    "CP Lounge Ubud": {
        "lat": -8.510837,
        "lng": 115.261847,
        "address": "CP Lounge, Jalan Monkey Forest, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Donna Ubud": {
        "lat": -8.513092,
        "lng": 115.260632,
        "address": "Donna, 67, Monkey Forest, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Room4Dessert": {
        "lat": -8.492696,
        "lng": 115.25325,
        "address": "Room4Dessert, Jalan Raya Sanggingan, Kedewatan, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Night Rooster": {
        "lat": -8.510354,
        "lng": 115.26393,
        "address": "The Night Rooster, Jalan Gautama Selatan, Ubud, Ubud District, Gianyar, Bali, 88571, Indonesia"
    },
    "Hujan Locale": {
        "lat": -8.507349,
        "lng": 115.265078,
        "address": "Hujan Locale, 5, Jalan Sri Wedari, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "The Blue Door Ubud": {
        "lat": -8.51419,
        "lng": 115.260504,
        "address": "The Blue Door, Jalan Monkey Forest, Ubud, Ubud District, Gianyar, Bali, 80751, Indonesia"
    },
    "No Mas Ubud": {
        "lat": -8.513965,
        "lng": 115.260555,
        "address": "No más, Jalan Monkey Forest, Ubud, Ubud District, Gianyar, Bali, 80751, Indonesia"
    },
    "Lazy Cats Cafe": {
        "lat": -8.505315,
        "lng": 115.258351,
        "address": "Lazy Cats Cafe, 23, Jalan Raya Ubud, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Apéritif Bali": {
        "lat": -8.493856,
        "lng": 115.27759,
        "address": "Apéritif Restaurant, Jalan Lanyahan, Gentong, Petulu, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Pison Ubud": {
        "lat": -8.518294,
        "lng": 115.263556,
        "address": "Pison Coffee, Jalan Raya Pengosekan, Ubud, Mas, Ubud District, Gianyar, Bali, 80751, Indonesia"
    },
    "Clear Cafe Ubud": {
        "lat": -8.50929,
        "lng": 115.264971,
        "address": "Clear Café, 8, Jalan Hanoman, Ubud, Ubud District, Gianyar, Bali, 88571, Indonesia"
    },
    "Tucky Ubud": {
        "lat": -8.509833,
        "lng": 115.2641,
        "address": "Tucky Speciality Coffee and Brunch, 15, Jalan Goutama, Ubud, Ubud District, Gianyar, Bali, 88571, Indonesia"
    },
    "The Elephant Ubud": {
        "lat": -8.49885,
        "lng": 115.25341,
        "address": "The Elephant, Jalan Raya Sanggingan, Sayan, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Seniman Coffee Studio": {
        "lat": -8.506732,
        "lng": 115.265198,
        "address": "Seniman Coffee Studio, 5, Jalan Sri Wedari, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Milk & Madu Ubud": {
        "lat": -8.506329,
        "lng": 115.262483,
        "address": "Milk and Madu, Jalan Suweta, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Suka Espresso Ubud": {
        "lat": -8.521135,
        "lng": 115.263213,
        "address": "Suka Espresso, Jalan Raya Pengosekan, Ubud, Mas, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Anomali Coffee Ubud": {
        "lat": -8.508213,
        "lng": 115.2652,
        "address": "Anomali Coffee, Jalan Raya Ubud, Ubud, Ubud District, Gianyar, Bali, 88571, Indonesia"
    },
    "RUSTERS Ubud": {
        "lat": -8.536528,
        "lng": 115.243593,
        "address": "Rusters, Jalan Raya Tebongkang, Kengetan, Singapadu Kaler, Sukawati, Gianyar, Bali, 80352, Indonesia"
    },
    "Pubas Coffee": {
        "lat": -8.496734,
        "lng": 115.266543,
        "address": "Pubas Coffee, Jalan Sri Wedari, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "KAFE Ubud": {
        "lat": -8.503451,
        "lng": 115.247709,
        "address": "Ubud Coffee Roastery, Jalan Cempaka Putih, Penestanan, Sayan, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Muse Cafe & Art": {
        "lat": -8.494162,
        "lng": 115.266455,
        "address": "Muse Cafe & Art, 6, Jalan Sri Wedari, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Monsieur Spoon Ubud": {
        "lat": -8.517301,
        "lng": 115.263755,
        "address": "Monsieur Spoon, Jalan Hanoman, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "FREAK Coffee Ubud": {
        "lat": -8.510203,
        "lng": 115.264901,
        "address": "Freak Coffee, Jalan Hanoman, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Yellow Flower Cafe": {
        "lat": -8.502161,
        "lng": 115.251847,
        "address": "Yellow Flower Cafe, Jalan Raya Sanggingan, Sayan, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Sacred Monkey Forest Sanctuary": {
        "lat": -8.518735,
        "lng": 115.25832,
        "address": "Sacred Monkey Forest Sanctuary, Ubud, Mas, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Campuhan Ridge Walk": {
        "lat": -8.499023,
        "lng": 115.255159,
        "address": "Campuhan Ridge Walk, Keliki, Tegallalang, Gianyar, Bali, 80561, Indonesia"
    },
    "Mason Adventures": {
        "lat": -8.717212,
        "lng": 115.205658,
        "address": "Mason Adventures, Adventure House, Jalan Bypass Ngurah Rai, Pemogan, South Denpasar, Denpasar, Bali, 80221, Indonesia"
    },
    "Tukad Cepung Waterfall": {
        "lat": -8.442321,
        "lng": 115.387903,
        "address": "Tukad Cepung Artifical Waterfall, Yangapi, Tembuku, Bangli, Bali, 80671, Indonesia"
    },
    "Goa Raja Waterfall": {
        "lat": -8.438434,
        "lng": 115.372333,
        "address": "Goa Raja waterfall, Bangli, Bali, 80614, Indonesia"
    },
    "Kanto Lampo Waterfall": {
        "lat": -8.532341,
        "lng": 115.332982,
        "address": "Kanto Lampo Waterfall, Gianyar, Bali, 80512, Indonesia"
    },
    "Tegenungan Waterfall": {
        "lat": -8.575229,
        "lng": 115.290701,
        "address": "Tegenungan Blangsinga Waterfall, Saba, Blahbatuh, Gianyar, Bali, 80581, Indonesia"
    },
    "Uma Anyar Waterfall": {
        "lat": -8.559202,
        "lng": 115.290071,
        "address": "Uma Anyar Waterfall ticket 1$, Kemenuh, Sukawati, Gianyar, Bali, 80582, Indonesia"
    },
    "Sumampan Waterfall": {
        "lat": -8.551766,
        "lng": 115.292124,
        "address": "Sumampan Waterfall, Buruan, Blahbatuh, Gianyar, Bali, 80581, Indonesia"
    },
    "Pengempu Waterfall": {
        "lat": -8.46915,
        "lng": 115.202808,
        "address": "Pengempu Waterfall, Cau Belayu, Marga, Tabanan, Bali, 82181, Indonesia"
    },
    "Manuaba Waterfall": {
        "lat": -8.443375,
        "lng": 115.290656,
        "address": "Manuaba WaterFall, Kenderan, Tegallalang, Gianyar, Bali, 80561, Indonesia"
    },
    "Suwat Waterfall": {
        "lat": -8.486301,
        "lng": 115.318034,
        "address": "Suwat, Gianyar, Bali, 80515, Indonesia"
    },
    "Goa Giri Campuhan Waterfall": {
        "lat": -8.463854,
        "lng": 115.388662,
        "address": "Goa Giri Campuhan (GGC) Waterfall, Nyanglan, Banjarangkan, Klungkung Regency, Bali, 80752, Indonesia"
    },
    "Tibumana Waterfall": {
        "lat": -8.506801,
        "lng": 115.333065,
        "address": "Tibumana Waterfall, Apuan, Susut, Bangli, Bali, 80661, Indonesia"
    },
    "Taman Sari Waterfall": {
        "lat": -8.502268,
        "lng": 115.328325,
        "address": "Taman Sari Waterfall tickets, Gang Rama, Bakbakan, Gianyar, Bali, 80752, Indonesia"
    },
    "Goa Rang Reng Waterfall": {
        "lat": -8.516205,
        "lng": 115.331305,
        "address": "Goa Rang Reng, Gianyar, Bali, 80515, Indonesia"
    },
    "Kuning Waterfall": {
        "lat": -8.491106,
        "lng": 115.360043,
        "address": "Air Terjun Kuning, Bangli, Bali, 80752, Indonesia"
    },
    "Leke Leke Waterfall": {
        "lat": -8.363692,
        "lng": 115.197989,
        "address": "Leke Leke Waterfall, Mekarsari, Baturiti, Tabanan, Bali, 82191, Indonesia"
    },
    "Campuhan Antapan Waterfall": {
        "lat": -8.359173,
        "lng": 115.194736,
        "address": "Campuhan Antapan waterfall, Antapan, Baturiti, Tabanan, Bali, 82191, Indonesia"
    },
    "Sekumpul Waterfall": {
        "lat": -8.17781,
        "lng": 115.182691,
        "address": "Sekumpul Waterfall, Lemukih, Sawan, Buleleng, Bali, 81171, Indonesia"
    },
    "Hidden Waterfall Bali": {
        "lat": -8.177681,
        "lng": 115.183542,
        "address": "Hidden Waterfall, Lemukih, Sawan, Buleleng, Bali, 81171, Indonesia"
    },
    "Tirta Buana Waterfall": {
        "lat": -8.205965,
        "lng": 115.16132,
        "address": "Tirta Buana Waterfall, Pegadungan, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Gitgit Waterfall": {
        "lat": -8.193562,
        "lng": 115.135075,
        "address": "Gitgit Waterfall, Gitgit, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Aling Aling Waterfall": {
        "lat": -8.176792,
        "lng": 115.106284,
        "address": "Aling-Aling Waterfall, Sambangan, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Kroya Waterfall": {
        "lat": -8.173772,
        "lng": 115.106589,
        "address": "Kroya Waterfall, Sambangan, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Kembar Waterfall": {
        "lat": -8.173189,
        "lng": 115.106513,
        "address": "Kembar Waterfall, Sambangan, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Pucak Waterfall": {
        "lat": -8.212875,
        "lng": 115.108825,
        "address": "Pucak Manik Waterfall, Wanagiri, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Jembong Waterfall": {
        "lat": -8.188702,
        "lng": 115.116541,
        "address": "Jembong Waterfall, Ambengan, Ambengan, Sukasada, Buleleng, Bali, 81161, Indonesia"
    },
    "Dedari Waterfall": {
        "lat": -8.499167,
        "lng": 115.356638,
        "address": "Dedari, Nyalian, Banjarangkan, Klungkung Regency, Bali, 80752, Indonesia"
    },
    "Munduk Waterfall": {
        "lat": -8.253656,
        "lng": 115.079382,
        "address": "Munduk Tutub Waterfall, Munduk, Banjar, Buleleng, Bali, 81152, Indonesia"
    },
    "Golden Valley Waterfall": {
        "lat": -8.254221,
        "lng": 115.073548,
        "address": "Golden Valley Waterfall, Munduk, Banjar, Buleleng, Bali, 81152, Indonesia"
    },
    "Banyuatis Waterfall": {
        "lat": -8.267276,
        "lng": 115.032986,
        "address": "Waterfall Banyuatis, Banyuatis, Banjar, Buleleng, Bali, 81152, Indonesia"
    },
    "Yeh Mampeh Waterfall": {
        "lat": -8.15425,
        "lng": 115.36009,
        "address": "Yeh Mempeh, Les, Tejakula, Bali, 81173, Indonesia"
    },
    "Jagasatru Waterfall": {
        "lat": -8.458407,
        "lng": 115.510624,
        "address": "Jagasatru, Duda Timur, Selat, Karangasem, Bali, 80862, Indonesia"
    },
    "Lower Yeh Labuh Waterfall": {
        "lat": -8.461495,
        "lng": 115.530714,
        "address": "Yeh Labuh - lower waterfall, Selumbung, Manggis, Karangasem, Bali, 80871, Indonesia"
    },
    "Upper Yeh Labuh Waterfall": {
        "lat": -8.460593,
        "lng": 115.530306,
        "address": "Yeh Labuh - upper waterfall, Selumbung, Manggis, Karangasem, Bali, 80871, Indonesia"
    },
    "Gembleng Waterfall": {
        "lat": -8.493209,
        "lng": 115.462294,
        "address": "Gembleng Waterfall, Tri Eka Buana, Sidemen, Karangasem, Bali, 80864, Indonesia"
    },
    "Ngurah Rai International Airport": {
        "lat": -8.746515,
        "lng": 115.16737,
        "address": "Ngurah Rai International Airport, Jalan Akses Bandara Ngurah Rai, Tuban, Denpasar, Badung, Bali, 80361, Indonesia"
    },
    "Singapore Changi Airport": {
        "lat": 1.351092,
        "lng": 103.994982,
        "address": "Singapore Changi Airport, T2 Departure Drive, Changi, East Region, Singapore, 819643, Singapore"
    },
    "Hard Rock Hotel Bali": {
        "lat": -8.721381,
        "lng": 115.171097,
        "address": "Hard Rock Hotel Bali, Jalan Pantai Kuta, Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Chez Monique Jewelry": {
        "lat": -8.501442,
        "lng": 115.266154,
        "address": "Chez Monique Jewelry Making, 57, Jalan Sri Wedari, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Cafe Lotus": {
        "lat": -8.50624,
        "lng": 115.261287,
        "address": "Cafe Lotus, Jalan Raya Ubud, Ubud, Ubud District, Gianyar, Bali, 88571, Indonesia"
    },
    "Ubud Palace": {
        "lat": -8.50695,
        "lng": 115.262737,
        "address": "Ubud Palace, Jalan Raya Ubud, Ubud, Ubud District, Gianyar, Bali, 80571, Indonesia"
    },
    "Goa Gajah Elephant Cave": {
        "lat": -8.523693,
        "lng": 115.286689,
        "address": "Goa Gajah, Jalan Raya Goa Gajah, Bedulu, Blahbatuh, Gianyar, Bali, 80581, Indonesia"
    },
    "Tegalalang Rice Terrace": {
        "lat": -8.433582,
        "lng": 115.279456,
        "address": "Tegallalang Rice Terraces, Tangkup, Kedisan, Tegallalang, Gianyar, Bali, 80561, Indonesia"
    },
    "Courtyard by Marriott Bali Seminyak Resort": {
        "lat": -8.691448,
        "lng": 115.163064,
        "address": "Courtyard Bali Seminyak Resort, 103, Jalan Camplung Tanduk, Seminyak, Kuta, Badung, Bali, 80361, Indonesia"
    },
    "Beachwalk Shopping Center": {
        "lat": -8.716546,
        "lng": 115.16931,
        "address": "Beachwalk Bali, Jalan Pantai Kuta, Kuta, Badung, Bali, 80361, Indonesia"
    }
};
